config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profile#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :reviews
  end
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :event_img, styles: { event_index: "250x350>", event_show: "325x475>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :event_img, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :event
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :find_event, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit]
  def index
    if params[:category].blank?
    @events = Event.all.order("created_at DESC")
  else
    @category_id = Category.find_by(name: params[:category]).id
    @events = Event.where(:category_id => @category_id).order("created_at DESC")
  end
end

  def show
    if @event.reviews.blank?
      @average_review = 0
    else
      @average_review = @event.reviews.average(:ratting).round(2)
    end
  end

  def new
    @event = current_user.events.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end
  def create
    @event = current_user.events.build(event_params)
    @event.category_id = params[:category_id]

    if @event.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @event.category_id = params[:category_id]
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end


  private

  def event_params
    params.require(:event).permit(:title, :lokasi, :jenis, :deskripsi, :category_id, :event_img)
  end

  def find_event
    @event = Event.find(params[:id])
end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_event
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.event_id = @event.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @review.update(review_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to event_path(@event)
  end

  private

  def review_params
    params.require(:review).permit(:ratting, :comment)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :multipart => true } do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
<%= f.file_field :event_img %>
<%= f.input :title, label: "Event Title" %>
<%= f.input :lokasi %>
<%= f.input :jenis %>
<%= f.input :deskripsi %>
<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/events/edit.html.erb
<div class="col-md6 col-md-offset-3">
  <div class="edit-event-form">

<h1>Edit Event</h1>

<%= simple_form_for @event, :html => { :multipart => true } do |f| %>
<%= f.select :category_id, @categories %>
<%= f.file_field :event_img %>
<%= f.input :title, label: "Event Title" %>
<%= f.input :lokasi %>
<%= f.input :jenis %>
<%= f.input :deskripsi %>
<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

</div>
</div>

app/views/events/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @events.count == 0 %>

  <h1 class="text-center">Event Yang Anda Cari Tidak Terdaftar :)</h1>

<% else %>

  <div class="row">

    <% @events.each do |event| %>
      <div class="col-md-3">

        <a href="/events/<%= event.id %>">
          <h3 class="btn btn-success text-center"><%= event.title %></h3>
          <%= image_tag event.event_img.url(:event_index), class: "event"%>


        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="col-md6 col-md-offset-3">
  <div class="new-event-form">
<h1>New Event</h1>
<%= render 'form' %>
</div>
</div

app/views/events/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag @event.event_img.url(:event_show), class: "event-show" %>
<div class="reviews">
  <h1>Penilaian Event</h1>
<%= render @event.reviews %>
<%= link_to "Add Review", new_event_review_path(@event), class: "btn-custom" %>
</div>


<div class="reviews">
  <% if user_signed_in? %>

    <% if @event.user_id == current_user.id %>
    <h3>Kelola postingan kamu</h3>
      <%= link_to "Back", root_path, class: "btn btn-custom" %>
      <%= link_to "Edit", edit_event_path(@event), class: "btn btn-custom" %>
      <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "apa kamu akan menghapus ini?"}, class: "btn btn-custom" %>
    <% end %>
  <% end %>
</div>
  </div>

  <div class="col-md-8">
    <div class="event-info">
    <h2 class="event-title">Nama Event : <%= @event.title %></h2>
    <h3 class="event-lokasi">Lokasi Event : <%= @event.lokasi %></h3>
    <p><%= @event.deskripsi %></p>
    <h3><div class="average-review-ratting" data-score=<%= @average_review %><h2>Rating Peminat </h2></div></h3>


  </div>
  </div>



  </div>





  <script>
    $('.review-ratting').raty({
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      },
      path: '/assets/'
    });
  </script>

  <script>
  $('.average-review-ratting').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventday</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style media="screen">
      .icon-soc {
        width: 50px;
        margin: 10px;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "EVENTDAY", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Profile Saya", profile_path%></li>
          <% end %>

        </ul>

        <ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expended="false">Categories
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>

                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, events_path(category: category.name), class: "link" %>
                </li>
              <% end %>

            </ul>
          </li>

          <% if user_signed_in? %>
            <li><%= link_to "Add Event", new_event_path %></li>
          <% end %>

        </ul>

      </div>

    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">

      <%= yield %>
    </div>

    <!--FOTERRRRRRR-->
    <footer style="background-color: #343a40 !important;padding:0px 0px;">
      <div class="footer-socmed" style="margin:90px 0px">
        <center>
          <div class="icons">
            <%= image_tag("facebook.png", :class => "icon-soc") %>
            <%= image_tag("twitter.png", :class => "icon-soc") %>
            <%= image_tag("yt.png", :class => "icon-soc") %>
            <%= image_tag("ig.png", :class => "icon-soc") %>
          </div>
          <div class="footer-nav">
            <strong style="color:white">HOME
              <span style="margin-left:12px">MENU
                <span style="margin-left:12px">STORY
                  <span style="margin-left:12px">LOCATIONS
                  </strong>
                  <br>
                  <p style="color:white">
                    EVENTDAY
                  </p>
                </div>
              </center>
            </div>
            <div class="footer-text" style="background-color: #28a745 !important;padding:20px 0px;">
              <center>
                <strong style="color:white">EVENTDAY</strong>
                <br>
                <p style="color:white">&copy Granada Project 2018 | All rights reserved.</p>
              </center>
            </div>

          </footer>

        </body>
      </html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@event, @event.reviews.build]) do |f| %>
<div id="ratting-form">
<label>Beri Kami Rating</label>
</div>


<%= f.input :comment %>
<%= f.button :submit, :class => "btn-custom2" %>
<% end %>
<script>
  $('#ratting-form').raty({
    path: '/assets',
    scoreName: 'review[ratting]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review-ratting" data-score="<%= review.ratting %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>

<% if review.user_id == current_user.id %>

<%= link_to "Edit", edit_event_review_path(review.event, review) %>
<%= link_to "Delete", event_review_path(review.event, review), method: :delete, data: {confirm: "Anda yakin?" } %>

<% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="col-md6 col-md-offset-3">
  <div class="edit-event-form">
<h1>Edit Review</h1>

<%= simple_form_for([@event, @review]) do |f| %>
<div id="ratting-form">
<label>Beri Kami Rating</label>
</div>
<%= f.input :comment %>
<%= f.button :submit, :class => "btn-custom2" %>
<% end %>
</div>
</div>

<script>
  $('#ratting-form').raty({
    path: '/assets',
    scoreName: 'review[ratting]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md6 col-md-offset-3">
  <div class="new-event-form">
<h1>New Review</h1>

<%= render 'form' %>

</div>
</div>